### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by nguyenthanhvuh** [viet-wics/viet-wics.github.io#1]
I think this website and its purpose is quite meaningful - thanks for doing it.  Several things you might want to add
- a database of scholarships/fellowships specific for women in CS 
- May be extend it to not just female but other minority too (I've written a post about supporting female/minority in CS PhD in https://nguyenthanhvuh.github.io/phd-cs-us/demystify.pdf#section.8.3
- Create a list of faculty who is recruiting or willing to mentor female in CS PhD (e.g., navigating the PhD admission and journey, search for jobs/interviews, etc).  For example, while I am not really recruiting new students, I am willing to help informally mentor fellow Vietnamese females in CS PhD.

**Comment by viet-wics** [comment]
That's great idea, thank you anh @nguyenthanhvuh !

1. I will definitely add more scholarship/ fellowships/ opportunities for Vietnamese woman in https://viet-wics.github.io/resource/
2. Yes! I agree! But for now (at least within the next 3 months), I'm doubt if I have time to extend to other minority. But no worries, this is just a beginning :D I'll strive to maintain this project during my minor study (at least in the next 2 years ;)
3. Awesome idea! I'll update it really soon.

P.s: As I mentioned in [FAQ](https://viet-wics.github.io/faq/), this project was also inspired by your [Viet-CS-Profs](https://github.com/dynaroars/dynaroars.github.io/wiki/Viet-CS-Profs-US)!

Thank you!
